# Generated by Django 4.1.9 on 2023-08-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="listing_id",),
        migrations.AlterField(
            model_name="contact",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.listing"
            ),
        ),
    ]
