# Generated by Django 4.1.9 on 2023-08-26 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("realtors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="realtor", name="email",),
        migrations.RemoveField(model_name="realtor", name="name",),
        migrations.AddField(
            model_name="realtor",
            name="realtor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
